highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: https//kirmayrtomaz.github.io/
author: Kirmayr Tomaz

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /curriculo/
title: Kirmayr Tomaz's Resume
name: Kirmayr Tomaz
email: tomaz.kirmayr@gmail.com
email_full: mailto:tomaz.kirmayr@gmail.com
website: kirmayztomaz.github.io
website_full: https://kirmayrtomaz.github.io
github: kirmayrtomaz
twitter: kirmayrtomaz
tel: +55 92992134199
tel_full: tel:+5592992134199
google_maps: 'https://www.google.co.uk/maps/place/R.+69,+24+-+Cidade+Nova,+Manaus+-+AM,+69094-510,+Brazil/@-2.9928154,-59.9760799,17z/data=!3m1!4b1!4m5!3m4!1s0x926c18fc1d7fc5b1:0x6fc510e717b75622!8m2!3d-2.9928208!4d-59.9738912'
address: Rua 69 casa 24
postcode: 69097578
city: Manaus
country: Amazonas
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
